version: '3.8'
services:
  app:
    build:
      context: ./php
    container_name: advertising_app
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - advertisingnet

  nginx:
    image: nginx:alpine
    container_name: advertising_nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - advertisingnet

  postgres:
    image: postgres:15
    container_name: advertising_pg
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: advertising_pg
    ports:
      - "5433:5432"
    networks:
      - advertisingnet
    volumes:
      - ../data/postgres:/var/lib/postgresql/data      

  redis:
    image: redis:alpine
    container_name: advertising_redis
    ports:
      - "6379:6379"
    networks:
      - advertisingnet
    volumes:
      - ../data/redis:/data      

  rabbitmq:
    image: rabbitmq:3-management
    container_name: advertising_rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - advertisingnet
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq      

  node_build:
    image: node:22-alpine
    container_name: advertising_node
    working_dir: /app
    volumes:
      - ../src:/app
    command: >
      sh -c "
        npm install &&
        npm run build
      "
    networks:
      - advertisingnet
    depends_on:
      - app      
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - advertisingnet          

networks:
  advertisingnet:
    driver: bridge

